version: '3'

services:
    goapi:
        build: .
        ports:
            - "5001:5002"
        links: 
            - postgres
        container_name: rocky3_server

    postgres:
        image: postgres:latest
        ports:
        - 5432:5432
        environment:
            POSTGRES_DB: 'mak'
            POSTGRES_USER: 'root'
            POSTGRES_PASS: 'root'
            POSTGRES_HOST_AUTH_METHOD: 'trust'

        container_name: mak_db

