version: "1.0"
services:
  dev:
    links: 
      -mysql
      
  mysql:
    image: 
    ports:
    - 5002:5002
    environment:
      MYSQLITE_DB: goDB
      MYSQLITE_USER: root
      MYSQLITE_PASSWORD: secret